/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package business;

import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import beans.BatchBean;
import beans.EmployeeBean;
import beans.PermissionBean;
import dao.BatchDao;
import daoimpl.BatchDaoImpl;
import daoimpl.RolePermissionDaoImpl;
import utility.CurrentDate;
import utility.UtilityMethods;

/**
 *
 * @author Amjad Ali Dahri
 */
public class BatchFrame extends javax.swing.JFrame {

    /**
     * Creates new form BatchForm
     */
    BatchDao batchDao = new BatchDaoImpl();
    EmployeeBean emp = null;

    public BatchFrame() {
        initComponents();
//        this.emp = LoginFrame.userBean;
        Toolkit t = Toolkit.getDefaultToolkit();
        this.setSize(t.getScreenSize().width, t.getScreenSize().height);
        this.getContentPane().setBackground(Color.white);
        this.setLocationRelativeTo(null);
        batchtable.getTableHeader().setFont(new Font("Tahoma",Font.BOLD,16));
        hideAllButtons();
        checkPermissions();
        populateBatchTable();
        clearFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        batchtxt = new javax.swing.JTextField();
        addlbl = new javax.swing.JLabel();
        updatelbl = new javax.swing.JLabel();
        deletelbl = new javax.swing.JLabel();
        resetlbl = new javax.swing.JLabel();
        batchLabel = new javax.swing.JLabel();
        searchtxt = new javax.swing.JTextField();
        searchLabel = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        batchHeader = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        batchtable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        batchtxt.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        batchtxt.setText("Enter batch name here");
        batchtxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        batchtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                batchtxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                batchtxtFocusLost(evt);
            }
        });
        batchtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                batchtxtMouseClicked(evt);
            }
        });

        addlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addbtn.png"))); // NOI18N
        addlbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addlblMouseClicked(evt);
            }
        });

        updatelbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/updatebtn.png"))); // NOI18N
        updatelbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updatelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatelblMouseClicked(evt);
            }
        });

        deletelbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deletebtn.png"))); // NOI18N
        deletelbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletelblMouseClicked(evt);
            }
        });

        resetlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resetbtn.png"))); // NOI18N
        resetlbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resetlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetlblMouseClicked(evt);
            }
        });

        batchLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        batchLabel.setText("Batch");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(deletelbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resetlbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(addlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updatelbl)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(batchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(batchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(batchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addlbl)
                    .addComponent(updatelbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deletelbl, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(resetlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(215, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 350, 510));

        searchtxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchtxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        searchtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchtxtKeyPressed(evt);
            }
        });
        getContentPane().add(searchtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 90, 220, 32));

        searchLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchLabel.setText("Search ");
        getContentPane().add(searchLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 90, -1, 32));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setOpaque(true);
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, -1, 770));

        close.setFont(new java.awt.Font("Century Gothic", 0, 34)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText("x");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 20, -1, 30));

        batchHeader.setBackground(new java.awt.Color(0, 102, 0));
        batchHeader.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        batchHeader.setForeground(new java.awt.Color(255, 255, 255));
        batchHeader.setText("                                                                                          BATCH");
        batchHeader.setOpaque(true);
        getContentPane().add(batchHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 70));

        batchtable.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        batchtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Batch ID", "Batch Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        batchtable.setRowHeight(20);
        batchtable.setRowMargin(2);
        batchtable.setSelectionBackground(new java.awt.Color(0, 102, 0));
        batchtable.getTableHeader().setResizingAllowed(false);
        batchtable.getTableHeader().setReorderingAllowed(false);
        batchtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                batchtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(batchtable);
        if (batchtable.getColumnModel().getColumnCount() > 0) {
            batchtable.getColumnModel().getColumn(0).setResizable(false);
            batchtable.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 990, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
//        new MainFrame().setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void batchtxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_batchtxtFocusGained
        if (batchtxt.getText().equals("Enter batch name here")) {
            batchtxt.setText("");
        }
    }//GEN-LAST:event_batchtxtFocusGained

    private void batchtxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_batchtxtFocusLost
        if (batchtxt.getText().isEmpty()) {
            batchtxt.setText("Enter batch name here");
        }
    }//GEN-LAST:event_batchtxtFocusLost

    private void addlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addlblMouseClicked
        BatchBean batch = new BatchBean();
        if (batchtable.getSelectedRow() == -1) {
            if (!batchtxt.getText().isEmpty() && !batchtxt.getText().equalsIgnoreCase("Enter batch name here")) {
                batch.setBatchName(batchtxt.getText());
                batch.setCreatedBy(emp.getEmpId());
                batch.setCreatedDate(CurrentDate.getCurrentDate() + "");
                if (batchDao.addBatch(batch) == 1) {
                    populateBatchTable();
                    batchtxt.setText("Enter batch name here");
                } else {
                    new MessageForm("Error", "Batch not added", "error.png").setVisible(true);
                }
            }
        } else {
            new MessageForm("Error", "Record is duplicate", "error.png").setVisible(true);
        }
    }//GEN-LAST:event_addlblMouseClicked

    private void deletelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletelblMouseClicked
        if(batchtable.getSelectedRow()!=-1){
        BatchBean batch = new BatchBean();
        batch.setBatchId(Integer.parseInt(batchtable.getValueAt(batchtable.getSelectedRow(), 0).toString()));
        batch.setModifiedBy(emp.getEmpId());
        batch.setModifiedDate(CurrentDate.getCurrentDate() + "");
        if (batchDao.deleteBatch(batch) == 1) {
            populateBatchTable();
            clearFields();
        } else {
            new MessageForm("Error", "Batch not deleted", "error.png").setVisible(true);
        }
        }else{
            new MessageForm("Error","No record selected","error.png").setVisible(true);
        }
    }//GEN-LAST:event_deletelblMouseClicked

    private void batchtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batchtableMouseClicked
        batchtxt.setText(batchtable.getValueAt(batchtable.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_batchtableMouseClicked

    private void updatelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatelblMouseClicked
        BatchBean batch = new BatchBean();
        if(batchtable.getSelectedRow()!=-1){
        if (!batchtxt.getText().isEmpty() && !batchtxt.getText().equalsIgnoreCase("Enter batch name here")) {
            batch.setBatchId(Integer.parseInt(batchtable.getValueAt(batchtable.getSelectedRow(), 0).toString()));
            batch.setBatchName(batchtxt.getText());
            batch.setModifiedBy(emp.getEmpId());
            batch.setModifiedDate(CurrentDate.getCurrentDate() + "");
            if (batchDao.updateBatch(batch) == 1) {
                populateBatchTable();
                clearFields();
            } else {
                new MessageForm("Error", "Batch not updated", "error.png");
            }
        }
        }else{
            new MessageForm("Error","No record selected","error.png").setVisible(true);
        }
    }//GEN-LAST:event_updatelblMouseClicked

    private void batchtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batchtxtMouseClicked
        if (batchtxt.getText().equalsIgnoreCase("Enter batch name here")) {
            batchtxt.setText("");
        }
    }//GEN-LAST:event_batchtxtMouseClicked

    private void searchtxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchtxtKeyPressed
        UtilityMethods.searchDataFromTable(batchtable, searchtxt);
    }//GEN-LAST:event_searchtxtKeyPressed

    private void resetlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetlblMouseClicked
        clearFields();
    }//GEN-LAST:event_resetlblMouseClicked

    private void populateBatchTable() {
        List<BatchBean> batches = batchDao.getAllBatches();
        DefaultTableModel dtm = (DefaultTableModel) batchtable.getModel();
        dtm.setRowCount(0);
        for (BatchBean batch : batches) {
            Object[] values = {batch.getBatchId(), batch.getBatchName()};
            dtm.addRow(values);
        }
        //UtilityMethods.fillDataIntoTables(rs, batchtable, jScrollPane1, this);
    }

    private void clearFields() {
        batchtxt.setText("Enter batch name here");
        batchtable.clearSelection();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BatchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BatchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BatchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BatchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        EmployeeBean emp = new EmployeeBean();
        emp.setEmpId(1);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BatchFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addlbl;
    private javax.swing.JLabel batchHeader;
    private javax.swing.JLabel batchLabel;
    private javax.swing.JTable batchtable;
    private javax.swing.JTextField batchtxt;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel close;
    private javax.swing.JLabel deletelbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel resetlbl;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JTextField searchtxt;
    private javax.swing.JLabel updatelbl;
    // End of variables declaration//GEN-END:variables

    private void hideAllButtons() {
        addlbl.setVisible(false);
        updatelbl.setVisible(false);
        deletelbl.setVisible(false);
    }

    private void checkPermissions() {
//        List<PermissionBean> permissions = new RolePermissionDaoImpl().getAssignedPermissions(LoginFrame.userBean.getRole());
//        for (PermissionBean pb : permissions) {
//            if (pb.getPermission().equals("Add Batch")) {
//                addlbl.setVisible(true);
//            }
//            if (pb.getPermission().equals("Update Batch")) {
//                updatelbl.setVisible(true);
//            }
//            if (pb.getPermission().equals("Delete Batch")) {
//                deletelbl.setVisible(true);
//            }
//        }
    }
}
