/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package business;

import beans.EmployeeBean;
import daoimpl.EmployeeDaoImpl;

/**
 *
 * @author Javed Ali Dahri
 */
public class ForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassword
     */
    EmployeeBean user = null;

    public ForgotPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        forgotHeader = new javax.swing.JLabel();
        usernametxt = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        submitanswerlbl = new javax.swing.JLabel();
        questionlbl = new javax.swing.JLabel();
        answerlbl = new javax.swing.JLabel();
        answertxt = new javax.swing.JTextField();
        submitlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText("X");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 20, 20));

        forgotHeader.setBackground(new java.awt.Color(0, 102, 0));
        forgotHeader.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        forgotHeader.setForeground(new java.awt.Color(255, 255, 255));
        forgotHeader.setText("                    Forgot Password");
        forgotHeader.setOpaque(true);
        jPanel1.add(forgotHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 490, 70));

        usernametxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        usernametxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(usernametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 360, 40));

        usernameLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        usernameLabel.setText("Username");
        jPanel1.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 90, 40));

        submitanswerlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/submitanswer.png"))); // NOI18N
        submitanswerlbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitanswerlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitanswerlblMouseClicked(evt);
            }
        });
        jPanel1.add(submitanswerlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 170, 40));

        questionlbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        questionlbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(questionlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 440, 40));

        answerlbl.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        answerlbl.setText("Answer");
        jPanel1.add(answerlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 70, 40));

        answertxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        answertxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(answertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 360, 40));

        submitlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/submitbtn.png"))); // NOI18N
        submitlbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitlblMouseClicked(evt);
            }
        });
        jPanel1.add(submitlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 100, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void submitlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitlblMouseClicked
        if (!usernametxt.getText().equals("")) {
            user = new EmployeeDaoImpl().getPassword(usernametxt.getText());
            if (user != null) {
                questionlbl.setText(user.getqId());
            } else {
                new MessageForm("Error", "Username is wrong", "error.png").setVisible(true);
            }
        } else {
            new MessageForm("Error", "Username is required", "error.png").setVisible(true);
        }
    }//GEN-LAST:event_submitlblMouseClicked

    private void submitanswerlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitanswerlblMouseClicked
        if (!questionlbl.getText().equals("")) {
            if (!answertxt.getText().equals("")) {
                if (user.getAnswer().equals(answertxt.getText())) {
                    new MessageForm("Success", "Your password : " + user.getPassword(), "success.png").setVisible(true);
                    clearFields();
                } else {
                    new MessageForm("Error", "Your answer is wrong", "error.png").setVisible(true);
                }
            } else {
                new MessageForm("Error", "Answer is required", "error.png").setVisible(true);
            }
        } else {
            new MessageForm("Error", "Security question is missed", "error.png").setVisible(true);
        }
    }//GEN-LAST:event_submitanswerlblMouseClicked
    
    private void clearFields() {
        usernametxt.setText("");
        questionlbl.setText("");
        answertxt.setText("");
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel answerlbl;
    private javax.swing.JTextField answertxt;
    private javax.swing.JLabel close;
    private javax.swing.JLabel forgotHeader;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel questionlbl;
    private javax.swing.JLabel submitanswerlbl;
    private javax.swing.JLabel submitlbl;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernametxt;
    // End of variables declaration//GEN-END:variables
}
