/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package business;

import daoimpl.SystemDaoImpl;

/**
 *
 * @author Javed Ali Dahri
 */
public class RegisterationFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegisterationFrame
     */
    public RegisterationFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        regHeader = new javax.swing.JLabel();
        regNoLabel = new javax.swing.JLabel();
        regtxt = new javax.swing.JTextField();
        registerBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText("X");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 10, 20));

        regHeader.setBackground(new java.awt.Color(0, 102, 0));
        regHeader.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        regHeader.setForeground(new java.awt.Color(255, 255, 255));
        regHeader.setText("                 Registeration Form");
        regHeader.setOpaque(true);
        jPanel1.add(regHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 60));

        regNoLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        regNoLabel.setText("Reg No");
        jPanel1.add(regNoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 60, 40));

        regtxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(regtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 370, 40));

        registerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_register.png"))); // NOI18N
        registerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerBtnMouseClicked(evt);
            }
        });
        jPanel1.add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void registerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBtnMouseClicked
        if(!regtxt.getText().equals("")){
            if(new SystemDaoImpl().insertMacAddress(regtxt.getText())==1){
                new MessageForm("Success","You are registered now","success.png").setVisible(true);
                this.dispose();
            }
        }else{
            new MessageForm("Error","Field is empty","error.png").setVisible(true);
        }
    }//GEN-LAST:event_registerBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel regHeader;
    private javax.swing.JLabel regNoLabel;
    private javax.swing.JLabel registerBtn;
    private javax.swing.JTextField regtxt;
    // End of variables declaration//GEN-END:variables
}
